### ISSUE TITLE
Aborting execution ???

### ISSUE THREAD

**Issue by ManarRashad** [IGS/portal_client#13]
I used this command 

```
./portal_client -m hmp_cart_289e823c35.tsv --endpoint-priority FASP,HTTP --user manar --debug
```
always give this error when I write the password
Unable to determine version.
```
2019-10-09 00:49:38,166 - root - DEBUG - In validate_cli.
2019-10-09 00:49:38,166 - aspera - DEBUG - In is_ascp_installed.
2019-10-09 00:49:38,166 - aspera - DEBUG - Installed? False
The ASCP binary is not installed or available.
Please install it or adjust yor PATH.
2019-10-09 00:49:38,166 - root - DEBUG - In obtain_password.
Enter your password: (masked)

2019-10-09 00:49:43,989 - root - ERROR - Aborting execution.
```

I don't know where is the problem , if the problem in ASCP installation 
I installed it from 
https://gist.github.com/mfansler/71f09c8b6c9a95ec4e759a8ffc488be3#file-install-ascp-sh
by changing its version and put it in the directory of portal_client

**Comment by victor73** [comment]
Before invoking portal_client, if you execute `ascp`, do you gete an error, or do you see the ascp usage information? `portal_client` needs ascp to be in your PATH when it is execute, and based on your log information, it can't find it: "The ASCP binary is not installed or available.
Please install it or adjust yor PATH."

**Comment by ManarRashad** [comment]
I download ascp and put it on the directory of portal_client
when I write the command "which ascp"
I have nothing no error or usage information like this:

```
(base) manar@manar-Dell-System-XPS-L502X:~/Documents/portal_client$ which ascp
(base) manar@manar-Dell-System-XPS-L502X:~/Documents/portal_client$ 
```

**Comment by victor73** [comment]
Right. The `ascp` tool can be installed anywhere you like, as long as it ends up being available through your shell's PATH. You'll know it's in your path when you get usage information when you type ascp with no arguments, or when you enter `which ascp` and you get its location in the output. If it's in your PATH when you run `portal_client`, then `portal_client` will find it...

**Comment by victor73** [comment]
Also, to see what directories are in your path, you can generally just run `echo $PATH` in most Unix/Linux environments.

**Comment by ManarRashad** [comment]
Thanks, the problem is solved but while downloading the data, this appears manytimes
Skipping file ID 76612bd9a41885add4f6b0b7682aff3e as none of the URLs ['FASP'] succeeded.
and sometimes get this:
MD5 check failed for the file ID 76612bd9a41885add4f6b0b7681477f2. Data may be corrupted.

while some files are downloaded 
Is it normal?

**Comment by victor73** [comment]
No, but to get around the checksum problem, you can additionally specify `--disable-validation` to your `portal_client` invocation. It would be helpful if you provided us which files/URLs you are getting those errors with.
