### ISSUE TITLE
username

### ISSUE THREAD

**Issue by colinbrislawn** [IGS/portal_client#17]
I'm interested in using this tool to download data from the HMP DACC
https://portal.hmpdacc.org/ 

What might my username be? The data is public, so is it possible that a username is not needed?
`--user myusername`

Thank you for your time!

**Comment by l4m6c** [comment]
Hi! If you want to use aspera sever to download the data you should ask for credentials here: https://www.hmpdacc.org/hmp/resources/download.php. The link is below the "Transferring Files To/From the Aspera Server:" paragraph.
