### ISSUE TITLE
Can't seem to install the portal_client

### ISSUE THREAD

**Issue by CH199** [IGS/portal_client#21]
I have been trying to download this for a couple hours now and can't seem to get it to work. I don't have any experience with python so that might be it.
When I try to download it, I get the following error message:

C:\Users\chiar\portal_client-master>pip install portal_client
ERROR: Could not find a version that satisfies the requirement portal_client (from versions: none)
ERROR: No matching distribution found for portal_client

portal_client-master is the folder downloaded from GitHub. 

What am I doing wrong?
Thanks for your help

**Comment by victor73** [comment]
There is a separate installation document that describes a few different methods for installation here: https://github.com/IGS/portal_client/blob/master/INSTALL.md
