### ISSUE TITLE
Downloading FASP URLs requires entering the password for every URL again

### ISSUE THREAD

**Issue by pbieberstein** [IGS/portal_client#5]
When downloading multiple FASP URLs via the Human Microbiome Project Data Portal manifest file I have to re-enter the password for every URL again. I can't find any way of specifying my password once so that the portal_client can use that for all the FASP URLs.

Am I overseeing something or is this a missing function?

Besides that, it seems to work great :)

**Comment by victor73** [comment]
Confirmed in v1.4.3. Thanks for pointing this out. This is definitely not how it should work...

**Comment by victor73** [comment]
Should be fixed in v1.4.4.
