### ISSUE TITLE
URL is present in manifest, but not accessible at the location specified

### ISSUE THREAD

**Issue by EunchongHuang** [IGS/portal_client#8]
Hello Victor, 

I am using the portal_client with a manifest file. This is the command that I ran: 

portal_client -m ibdmbd_16s_3ffb7fc0cc.tsv --endpoint-priority FASP,HTTP --user hec1324

I realized that in the manifest file, every url that starts with fasp://aspera.... works and completed download but urls that start with fas://apsera2 do not work. At the end, it says "URL is present in manifest, but not accessible at the location specified."

I have ran debug process with the command: portal_client -m ibdmbd_16s_3ffb7fc0cc.tsv --endpoint-priority FASP,HTTP --user hec1324 --debug and gave me an error: 

019-07-11 11:21:55,575 - aspera - DEBUG - In get_ascp_env.
2019-07-11 11:21:55,575 - aspera - INFO - Setting ASPERA_SCP_PASS environment variable.
2019-07-11 11:21:55,577 - aspera - INFO - Beginning transfer.
2019-07-11 11:21:59,159 - aspera - INFO - Invocation of ascp complete. Return code: 1.
2019-07-11 11:21:59,159 - aspera - **ERROR - Aspera authentication failure.**
2019-07-11 11:21:59,160 - manifest_processor.ManifestProcessor - **ERROR - Aspera transfer failed.**
2019-07-11 11:21:59,160 - manifest_processor.ManifestProcessor - DEBUG - Returning error
Skipping file ID d39c1941c8f6e8b0f6ead5d7f75419c3 as none of the URLs ['FASP'] succeeded.

In this case, what should I do? 
Thank you so much for your help.

**Comment by victor73** [comment]
Hello,

There should be no URLs that have "fas://" as the protocol. It should include a "p": "fasp://". Can you confirm that you have that in your manifest, or if it was a typo? Also, it should be "aspera", not "apsera2". Can you paste the relevant portion of the manifest file you have that is showing these typos?

**Comment by EunchongHuang** [comment]
Thank you for your response. 

Sorry for the typo error. 
The manifest file that I'm struggling with is shown below: 
<img width="758" alt="스크린샷 2019-07-19 오후 2 01 44" src="https://user-images.githubusercontent.com/51738181/61510433-ca8d0300-aa2d-11e9-81c3-fdc01fb0f5c4.png">

The manifest file that works fine is also shown below: 
<img width="388" alt="스크린샷 2019-07-19 오후 2 03 09" src="https://user-images.githubusercontent.com/51738181/61510478-fad4a180-aa2d-11e9-8fc5-dc1d76207a77.png">

**Comment by victor73** [comment]
Yes, please replace all instances of "aspera2" with just "aspera", and it should then work properly...

**Comment by EunchongHuang** [comment]
Thank you for your comment! 
It works fine!!
